# Generated by Django 2.1.4 on 2019-01-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('nome_arquivo', models.CharField(max_length=50)),
            ],
        ),
    ]
