# Generated by Django 2.1.4 on 2019-01-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='operacao',
            name='duracao',
            field=models.DurationField(),
        ),
    ]
