# Generated by Django 2.1.4 on 2019-01-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190103_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='file',
            field=models.CharField(default='', max_length=50),
        ),
    ]
