# Generated by Django 2.1.4 on 2019-01-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operacao_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
