# Generated by Django 2.1 on 2019-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190103_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='duracao',
            field=models.DurationField(help_text='Use format: <em>11:11:11</em>.'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='endtime',
            field=models.TimeField(help_text='Please use the following format: <em>11:11:11</em>.'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='startime',
            field=models.TimeField(help_text='Please use the following format: <em>11:11:11</em>.'),
        ),
    ]
