# Generated by Django 2.1 on 2019-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190104_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='video',
        ),
        migrations.AddField(
            model_name='operacao',
            name='video',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default='', upload_to='uploads/', verbose_name='arquivo txt'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='titulo do video'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome do arquivo'),
        ),
    ]
